In [1]:
countries=("India China Canada America British").split()
countries

['India', 'China', 'Canada', 'America', 'British']

# both the variables pointing to same id

In [2]:
l=countries
l.append("Spain")
countries

['India', 'China', 'Canada', 'America', 'British', 'Spain']

In [3]:
l=countries[:]
l.append("France")
l

['India', 'China', 'Canada', 'America', 'British', 'Spain', 'France']

In [4]:
countries

['India', 'China', 'Canada', 'America', 'British', 'Spain']

In [5]:
s=countries.copy()
s.append("Russia")

In [6]:
countries

['India', 'China', 'Canada', 'America', 'British', 'Spain']

In [1]:
import os
os.getcwd()

'C:\\Users\\Dell'

In [11]:
import numpy as np
np.random.randint(0,5,4)

array([0, 4, 2, 1])

In [1]:
l=["hii",'there','hey']
l2=['whatup','by','where']
l.extend(l2)
l

['hii', 'there', 'hey', 'whatup', 'by', 'where']

In [2]:
l.append(l2)
l

['hii', 'there', 'hey', 'whatup', 'by', 'where', ['whatup', 'by', 'where']]

In [40]:
print('\033[92mThis is a color')

This is a color


In [1]:
import tensorflow as tf

In [6]:
print(len(tf.config.experimental.list_physical_devices('GPU')))

1


In [3]:
tf.test.is_built_with_cuda()

True

In [16]:
gpu_devices = tf.config.list_physical_devices('GPU')
gpu_devices


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
np.mean([23,54])

38.5

In [8]:
d={'items':[1,2,3,4],'prices':[122,344,555]}
d.get("items")

[1, 2, 3, 4]

In [9]:
for x,y in d.items():
    print(x,y) 

items [1, 2, 3, 4]
prices [122, 344, 555]


In [2]:
import json
dic={'name':'Anurag',
    'Branch':'AIDS'}
with open('base.json','w') as f:
    f.write(json.dumps(dic))


In [1]:
import tensorflow as tf

In [2]:
tf._

'2.12.0'

In [11]:
l=['the','and']
s='the and or'
s.split()

['the', 'and', 'or']

In [1]:
import nltk

In [2]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...


True

In [3]:
from nltk.sentiment import SentimentIntensityAnalyzer

In [4]:
sia=SentimentIntensityAnalyzer()

In [6]:
sia.polarity_scores('This is the worst day ever')

{'neg': 0.451, 'neu': 0.549, 'pos': 0.0, 'compound': -0.6249}

In [18]:
array=np.array([1,2,3,4])
zero=np.zeros(10)
zero


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.concatenate((array,zero))


array([1., 2., 3., 4., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [1]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [24]:
import tensorflow as tf

In [2]:
daily_sales_num=[20,100,230,-45,811,-843]

In [3]:
tf_dataset=tf.data.Dataset.from_tensor_slices(daily_sales_num) 

In [4]:
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

20
100
230
-45
811
-843


In [5]:
l=list(tf_dataset)
l

[<tf.Tensor: shape=(), dtype=int32, numpy=20>,
 <tf.Tensor: shape=(), dtype=int32, numpy=100>,
 <tf.Tensor: shape=(), dtype=int32, numpy=230>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-45>,
 <tf.Tensor: shape=(), dtype=int32, numpy=811>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-843>]

In [9]:
tf_dataset = tf_dataset.filter(lambda X: X>0)
print(list(tf_dataset.as_numpy_iterator()))

[20, 100, 230, 811]


In [13]:
for sales in tf_dataset.take(3).as_numpy_iterator():
    print(sales)

20
100
230


In [20]:
tf_dataset.shuffle(buffer_size=2)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

20
100
230
811


In [23]:
for sales in tf_dataset.batch(2).as_numpy_iterator():
    print(sales)

[ 20 100]
[230 811]


In [26]:
images_ds=tf.data.Dataset.list_files('/Users/Dell/*')
for file in images_ds.take(5):
    print(file.numpy())

b'\\Users\\Dell\\Templates'
b'\\Users\\Dell\\NTUSER.DAT'
b'\\Users\\Dell\\Links'
b'\\Users\\Dell\\ntuser.dat.LOG2'
b'\\Users\\Dell\\Documents'


In [27]:
import os
def get_label(file_path):
    return tf.strings.split(file_path,os.path.sep)[-1]
    

In [32]:
images_ds.map(get_label)
for file in images_ds.map(get_label).take(5):
    print(file.numpy())

b'Downloads'
b'Recent'
b'Searches'
b'NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TMContainer00000000000000000001.regtrans-ms'
b'Music'
